"""Auto-generate organization aliases map using fuzzy matching."""

import json
from pathlib import Path
from collections import defaultdict
import yaml
from thefuzz import fuzz

def normalize_for_match(name: str) -> str:
    """Normalize organization name for matching purposes."""
    name = name.lower()
    # Remove common suffixes that cause false negatives
    for suffix in [" inc", " inc.", " llc", " foundation", " (org)", " org"]:
        if name.endswith(suffix):
            name = name[:-len(suffix)]
    
    # Replace common separators
    name = name.replace("-", " ").replace("–", " ").replace(",", "")
    return name.strip()

def main():
    data_dir = Path("Data")
    if not data_dir.exists():
        print(f"Error: {data_dir} not found.")
        return

    # Collect all unique names across all years
    all_names = set()
    for file in data_dir.glob("*.json"):
        with open(file, "r", encoding="utf-8") as f:
            data = json.load(f)
            for org in data.get("organizations", []):
                all_names.add(org["name"])
    
    all_names = sorted(list(all_names))
    print(f"Found {len(all_names)} unique organization names.")

    # Group similar names
    groups = []
    used_names = set()

    for i, name1 in enumerate(all_names):
        if name1 in used_names:
            continue
            
        current_group = [name1]
        used_names.add(name1)
        norm1 = normalize_for_match(name1)
        
        for name2 in all_names[i+1:]:
            if name2 in used_names:
                continue
                
            norm2 = normalize_for_match(name2)
            
            # Use token sort ratio which handles word reordering well
            # Also check if normalized strings are exactly equal
            score = fuzz.token_sort_ratio(norm1, norm2)
            
            if norm1 == norm2 or score > 90:
                current_group.append(name2)
                used_names.add(name2)
        
        if len(current_group) > 1:
            groups.append(current_group)

    print(f"Found {len(groups)} potential alias groups.")

    # Build the YAML structure
    aliases_yaml = {
        "aliases": {}
    }
    
    for group in groups:
        # Pick the shortest name as canonical, or the one that looks most "standard"
        canonical = min(group, key=len)
        aliases = [name for name in group if name != canonical]
        aliases_yaml["aliases"][canonical] = aliases
    
    # Save to config file
    config_dir = Path("d:/Projects/GSoCPathfinder/src/config")
    config_dir.mkdir(parents=True, exist_ok=True)
    out_file = config_dir / "org_aliases.yaml"
    
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("# GSoC Pathfinder — Organization Aliases Map\n")
        f.write("# Auto-generated by scripts/generate_aliases.py\n")
        f.write("# Review and edit this file to ensure correct canonical names and aliases.\n\n")
        yaml.dump(aliases_yaml, f, allow_unicode=True, default_flow_style=False, sort_keys=True)
        
    print(f"Generated aliases map at {out_file}")
    print("Please review the file and correct any false positives or missing aliases.")

if __name__ == "__main__":
    main()
